### PR TITLE
several proposed fixes for libzfs_core-wip branch

### PR DESCRIPTION
**Pull request by avg-I**
@ryao I am not sure that all of the proposed changes are correct.
Could you please review them?  And either merge them into your branch or discuss them further.

### CODE REVIEW

**Comment by ryao** [comment]
@avg-I I have pushed the 3 commits to the branch and also a commit intended to address the issue that you pointed out. I need to do more testing with bookmarks to verify that the behavior is the same, but it is definitely correct for pools that lack bookmarks.

**Comment by avg-I** [comment]
The branch has been rebased to the latest ClusterHQ/zfs/libzfs_core-wip

**Comment by ryao** [comment]
@avg-I The correct thing here is to change the check to `>= 1` rather than remove it.

**Comment by ryao** [comment]
I have pushed the fix.

**Pull request closed without merging**
